/*
## Question
If two students A and B are friends, 
and A likes B but not vice-versa, 
remove the Likes tuple.

##

--- A LIKE B BUT B NOT LIKE A
SELECT *
FROM Likes L1
WHERE NOT EXISTS(
	SELECT *
	FROM Likes L2
	WHERE L1.ID1 = L2.ID2 AND L1.ID2 = L2.ID1
);

SELECT L1.ID1, L1.ID2
FROM Likes L1
LEFT JOIN Likes L2
ON L1.ID1 = L2.ID2 AND L1.ID2 = L2.ID1
WHERE L2.ID1 IS NULL;

SELECT * FROM Likes 
EXCEPT 
SELECT L2.ID2 AS 'ID1', L2.ID1 AS 'ID2' FROM Likes L2;
*/


/*
## ANS

--- (A Likes B) AND (A Friend B)
SELECT * 
FROM Likes AS L1
WHERE EXISTS(
	SELECT *
	FROM Friend AS F
	WHERE L1.ID1 = F.ID1 AND L1.ID2 = F.ID2
);

--- (A Likes B) AND (A Friend B) AND (B NOT Likes A)
SELECT * 
FROM Likes AS L1
WHERE EXISTS(
	SELECT *
	FROM Friend AS F
	WHERE L1.ID1 = F.ID1 AND L1.ID2 = F.ID2
) AND NOT EXISTS(
	SELECT *
	FROM Likes AS L2
	WHERE L1.ID1 = L2.ID2 AND L1.ID2 = L2.ID1 
);

*/
DELETE FROM Likes AS L1
WHERE EXISTS(
	SELECT *
	FROM Friend AS F
	WHERE L1.ID1 = F.ID1 AND L1.ID2 = F.ID2
) AND NOT EXISTS(
	SELECT *
	FROM Likes AS L2
	WHERE L1.ID1 = L2.ID2 AND L1.ID2 = L2.ID1 
);
